### ISSUE TITLE
Warnings of unused code

### ISSUE THREAD

**Issue by Pjino** [TheSquad/Plug-Range#4]
When I was compiling my project I got two warnings:

warning: variable p is unused
  lib/plug_range.ex:40

warning: unused import Plug.Conn
  lib/plug_range.ex:4

Although it's not important it frees the console.

PS: This plug is being super helpful. Thanks!

**Comment by TheSquad** [comment]
Yup, no problem, it is fixed...

**Comment by Pjino** [comment]
Thank you!
