### ISSUE TITLE
Warnings in Elixir 1.4

### ISSUE THREAD

**Issue by Pjino** [TheSquad/Plug-Range#5]
There are a few simple warnings that could be removed.

**Comment by TheSquad** [comment]
I haven't yet migrated my project to Elixir 1.4... you are welcome to make a pull request

**Comment by Pjino** [comment]
I will do it...someday, but for now I've never done any and don't feel that I'm comfortable enough to know how to do it correctly end to end :)

**Comment by frostpuppet** [comment]
this should do it:

  def project do
    [app: :plug_range,
     version: "0.0.2",
     elixir: "~> 1.2",
     description: description(),
     package: package(),
     build_embedded: Mix.env == :prod,
     start_permanent: Mix.env == :prod,
     deps: deps()]
  end

**Comment by scouten** [comment]
FWIW I have a PR open against plug itself to support range queries. Loosely based on this 
module.

https://github.com/elixir-lang/plug/pull/526

**Comment by TheSquad** [comment]
That would be great...
Until then, I have pushed  to master the fix for warnings
